from typing import Annotated, Any, Optional
from typing_extensions import TypedDict
from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    """
    Central cognitive state for the SecFlow Analyzer Agent.
    Maintains repository snapshot context, conversation history,
    inspection artifacts, and iteration counters.
    """
    # Append-only message history for ReAct reasoning and tool invocations
    messages: Annotated[list[AnyMessage], add_messages]

    # Normalized YAML snapshot data generated by Team 1
    snapshot_data: dict[str, Any]

    # Absolute path to the isolated repository workspace sandbox
    workspace_path: str

    # Raw JSON string drafted by the LLM before schema validation
    manifest_draft: Optional[str]

    # Captured Pydantic schema errors fed back for self-correction
    validation_errors: list[str]

    # Execution counter to guard against infinite reasoning loops (max 15)
    iteration_count: int