# pyrefly: ignore [missing-import]
import json
from pathlib import Path
import pytest
import yaml

from app.analyzer.services.analyzer_service import run_analyzer_workflow


@pytest.fixture
def sample_workspace(tmp_path: Path) -> Path:
    """
    Constructs a controlled sandbox workspace mimicking a real repository
    with a snapshot file and sample entry-point source code.
    """
    ws = tmp_path / "sample_repo"
    ws.mkdir()

    # 1. Create a dummy entry point source file
    main_py = ws / "main.py"
    main_py.write_text(
        '"""Sample API Service Entrypoint."""\n'
        'from fastapi import FastAPI\n'
        'app = FastAPI(title="SecFlow Target App")\n'
        '@app.get("/health")\n'
        'def health():\n'
        '    return {"status": "ok"}\n',
        encoding="utf-8",
    )

    # 2. Create sample Dockerfile
    dockerfile = ws / "Dockerfile"
    dockerfile.write_text("FROM python:3.11-slim\nCMD [\"python\", \"main.py\"]\n", encoding="utf-8")

    # 3. Create repository_snapshot.yaml generated by Team 1
    snapshot_data = {
        "repository": {
            "name": "SecFlow Target App",
            "type": "web_application",
        },
        "languages": [{"name": "Python", "percentage": 100.0}],
        "technologies": [
            {"name": "FastAPI", "category": "framework"}
        ],
        "dependencies": ["fastapi", "uvicorn"],
    }

    snapshot_file = ws / "repository_snapshot.yaml"
    with open(snapshot_file, "w", encoding="utf-8") as f:
        yaml.dump(snapshot_data, f)

    return ws


def test_analyzer_e2e_execution(sample_workspace: Path, monkeypatch):
    """
    Tests end-to-end analyzer execution with a mock LLM returning valid JSON
    to verify pipeline orchestration, artifact saving, and boundary enforcement.
    """
    from langchain_core.messages import AIMessage

    mock_manifest = {
        "project": {
            "name": "SecFlow Target App",
            "type": "web_application",
            "description": "Validated target application",
            "primary_purpose": "API testing and health monitoring",
        },
        "actors": [{"name": "Developer", "role": "Maintainer"}],
        "technologies": [
            {
                "name": "FastAPI",
                "category": "framework",
                "evidence": [{"file_path": "main.py", "description": "Entry file"}],
            }
        ],
        "architecture": {
            "pattern": "monolith",
            "entry_points": ["main.py"],
            "core_components": ["API Router"],
            "data_flow_summary": "HTTP request to FastAPI health handler",
        },
        "deployment": {
            "containerized": True,
            "configs": ["Dockerfile"],
            "target_platforms": ["Docker"],
        },
        "key_dependencies": ["fastapi"],
        "confidence_score": 0.99,
        "evidence_ledger": [],
    }

    # Intercept LLM invoke in nodes to provide deterministic response during E2E test
    class StubLLM:
        def invoke(self, messages):
            return AIMessage(content=json.dumps(mock_manifest))
        def bind_tools(self, tools):
            return self

    monkeypatch.setattr("app.analyzer.graph.nodes.get_model", lambda tools=None: StubLLM())

    # Execute workflow orchestrator
    result = run_analyzer_workflow(str(sample_workspace))

    # Assertions
    assert result["iteration_count"] >= 1
    assert result["validation_errors"] == []
    assert result["manifest"]["project"]["name"] == "SecFlow Target App"

    # Verify physical file persistence on disk
    json_artifact = sample_workspace / "project_manifest.json"
    html_artifact = sample_workspace / "manifest.html"

    assert json_artifact.exists()
    assert html_artifact.exists()

    # Validate output JSON integrity
    with open(json_artifact, "r", encoding="utf-8") as f:
        persisted_data = json.load(f)
    assert persisted_data["confidence_score"] == 0.99